"use client";

import { motion } from "framer-motion";

import {
  Sparkles,
  Brain,
  TrendingUp,
} from "lucide-react";


import {
  GlassCard,
} from "@/components/ui/GlassCard";


import {
  GlowIcon,
} from "@/components/ui/GlowIcon";


import {
  useSoulMemoryStore,
} from "@/store/soul-memory-store";



export function LatestInsight() {


  const {
    insight,
    archetype,
    emotion,
  } =
    useSoulMemoryStore();




  const score =
    insight
      ? 92
      : 0;





  return (

<section

className="
relative
mx-auto
mt-24
w-full
max-w-6xl
px-6
"

>



<motion.div

initial={{
opacity:0,
y:30,
}}

whileInView={{
opacity:1,
y:0,
}}

viewport={{
once:true,
}}

transition={{
duration:0.8,
}}

>


<GlassCard

highlight

className="
relative
overflow-hidden
p-8
md:p-10
"

>




<div

className="
pointer-events-none
absolute
right-0
top-0
h-80
w-80
rounded-full
bg-[#D6B25E]/10
blur-[120px]
"

/>






<div

className="
relative
z-10
flex
flex-col
gap-10
lg:flex-row
lg:items-center
lg:justify-between
"

>



<div

className="
max-w-3xl
"

>



<div

className="
flex
items-center
gap-4
"

>



<GlowIcon size="lg">


<Sparkles

size={22}

className="
text-[#D6B25E]
"

/>


</GlowIcon>




<div>


<p

className="
text-[11px]
uppercase
tracking-[0.45em]
text-[#D6B25E]
"

>

Latest Intelligence

</p>


<p

className="
mt-2
text-xs
text-white/40
"

>

Generated by EON Intelligence Engine

</p>


</div>


</div>







<h2

className="
mt-8
font-[family:var(--font-cormorant)]
text-4xl
font-light
leading-tight
text-[#F4F1EA]
md:text-5xl
"

>


{
insight
?
"Your personal intelligence pattern has been revealed."
:
"Your intelligence journey begins with your first reflection."
}


</h2>







<p

className="
mt-6
leading-8
text-white/60
"

>


{
insight
?
insight
:
"Complete a Soul Scan to discover hidden emotional patterns, archetypes and personal insights."
}


</p>








<div

className="
mt-8
flex
flex-wrap
gap-3
"

>



{
[
archetype || "Identity",
emotion || "Emotion",
"Evolution",
].map(
(tag)=>(
<span

key={tag}

className="
rounded-full
border
border-[#D6B25E]/20
bg-[#D6B25E]/5
px-4
py-2
text-[10px]
uppercase
tracking-[0.3em]
text-[#D6B25E]
"

>

{tag}

</span>
)

)

}




</div>



</div>









<motion.div

animate={{
y:[0,-8,0],
}}

transition={{
duration:5,
repeat:Infinity,
}}

className="
min-w-[240px]
rounded-3xl
border
border-[#D6B25E]/20
bg-black/30
p-7
"

>



<div

className="
flex
items-center
gap-3
"

>


<Brain

size={18}

className="
text-[#D6B25E]
"

/>



<p

className="
text-[10px]
uppercase
tracking-[0.35em]
text-[#D6B25E]
"

>

Growth Index

</p>


</div>







<h3

className="
mt-5
text-5xl
font-light
text-[#F4F1EA]
"

>

{
score
?
`${score}%`
:
"--"
}

</h3>







<div

className="
mt-6
h-1.5
overflow-hidden
rounded-full
bg-white/10
"

>



<motion.div

initial={{
width:0,
}}

whileInView={{
width:`${score}%`,
}}

viewport={{
once:true,
}}

transition={{
duration:1.2,
}}

className="
h-full
rounded-full
bg-[#D6B25E]
"

/>



</div>








<div

className="
mt-6
flex
items-center
gap-2
text-xs
text-white/40
"

>


<TrendingUp

size={14}

className="
text-[#D6B25E]
"

/>


{

score
?
"Continuous evolution"
:
"Awaiting first analysis"

}


</div>






</motion.div>





</div>







<div

className="
relative
z-10
mt-10
border-t
border-white/10
pt-5
"

>


<p

className="
text-[10px]
uppercase
tracking-[0.4em]
text-white/30
"

>

Powered by EON Intelligence Engine • Growth Layer

</p>


</div>





</GlassCard>



</motion.div>


</section>


);

}