
"use client";

import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";

import { GlassCard } from "@/components/ui/GlassCard";
import { GlowIcon } from "@/components/ui/GlowIcon";


export function LatestInsight() {
  return (

    <section
      className="
      mx-auto
      mt-16
      w-full
      max-w-5xl
      px-6
      "
    >

      <motion.div

        initial={{
          opacity:0,
          y:25,
        }}

        whileInView={{
          opacity:1,
          y:0,
        }}

        viewport={{
          once:true,
        }}

        transition={{
          duration:0.6,
        }}

      >

        <GlassCard
          highlight
          className="
          p-6
          md:p-8
          "
        >

          <div
            className="
            flex
            flex-col
            gap-8
            lg:flex-row
            lg:items-center
            lg:justify-between
            "
          >


            <div
              className="
              max-w-2xl
              "
            >


              <div
                className="
                flex
                items-center
                gap-4
                "
              >

                <GlowIcon>

                  <Sparkles
                    size={20}
                    className="text-[#D6B25E]"
                  />

                </GlowIcon>


                <div>

                  <p
                    className="
                    text-[11px]
                    uppercase
                    tracking-[0.35em]
                    text-[#D6B25E]
                    "
                  >
                    Latest Insight
                  </p>


                  <p
                    className="
                    mt-1
                    text-xs
                    text-white/40
                    "
                  >
                    Generated by Soul AI
                  </p>

                </div>


              </div>


              <h2
                className="
                mt-6
                font-[family:var(--font-cormorant)]
                text-3xl
                font-light
                leading-tight
                text-[#F4F1EA]
                md:text-4xl
                "
              >
                "You have been relying on logic,
                while your intuition keeps asking
                to be heard."
              </h2>


              <p
                className="
                mt-5
                text-base
                leading-7
                text-white/60
                "
              >
                This pattern appeared across your
                reflections and dreams. Your subconscious
                keeps pointing toward trusting yourself.
              </p>


            </div>



            <motion.div

              animate={{
                y:[0,-8,0],
              }}

              transition={{
                duration:5,
                repeat:Infinity,
              }}

              className="
              min-w-[220px]
              rounded-3xl
              border
              border-[#D6B25E]/20
              bg-black/30
              p-6
              "

            >

              <p
                className="
                text-[11px]
                uppercase
                tracking-[0.3em]
                text-[#D6B25E]
                "
              >
                Confidence
              </p>


              <h3
                className="
                mt-3
                text-5xl
                font-light
                text-[#F4F1EA]
                "
              >
                92%
              </h3>


              <div
                className="
                mt-5
                h-1.5
                overflow-hidden
                rounded-full
                bg-white/10
                "
              >

                <motion.div

                  initial={{
                    width:0,
                  }}

                  whileInView={{
                    width:"92%",
                  }}

                  viewport={{
                    once:true,
                  }}

                  transition={{
                    duration:1.2,
                  }}

                  className="
                  h-full
                  rounded-full
                  bg-[#D6B25E]
                  "

                />

              </div>


            </motion.div>


          </div>


        </GlassCard>


      </motion.div>


    </section>

  );
}

