"use client";

import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";

export function LatestInsight() {
  return (
    <section className="mx-auto mt-24 w-full max-w-7xl px-6">
      <motion.div
        initial={{ opacity: 0, y: 35 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6 }}
        className="relative overflow-hidden rounded-[40px] border border-white/10 bg-white/[0.03] p-10 backdrop-blur-3xl"
      >
        {/* Glow */}
        <div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-[#D6B25E]/10 blur-[140px]" />

        <div className="relative z-10 flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between">

          <div className="max-w-3xl">

            <div className="mb-6 flex items-center gap-3">

              <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#D6B25E]/10">
                <Sparkles
                  size={22}
                  className="text-[#D6B25E]"
                />
              </div>

              <div>
                <p className="text-xs uppercase tracking-[0.35em] text-[#D6B25E]/80">
                  Latest Insight
                </p>

                <p className="text-white/40">
                  Generated by Soul AI
                </p>
              </div>

            </div>

            <h2 className="font-[family:var(--font-cormorant)] text-5xl leading-tight text-[#F4F1EA]">
              "You have been relying on logic,
              while your intuition keeps asking
              to be heard."
            </h2>

            <p className="mt-8 max-w-2xl text-lg leading-8 text-white/60">
              This pattern has appeared in your latest
              reflections and dreams. Your subconscious
              consistently points toward trusting yourself
              before seeking certainty from others.
            </p>

          </div>

          <motion.div
            animate={{
              y: [0, -12, 0],
            }}
            transition={{
              duration: 5,
              repeat: Infinity,
            }}
            className="rounded-3xl border border-[#D6B25E]/20 bg-[#09090B]/70 p-8 backdrop-blur-3xl"
          >
            <p className="text-xs uppercase tracking-[0.3em] text-[#D6B25E]/70">
              Confidence
            </p>

            <h3 className="mt-4 text-7xl font-light text-[#F4F1EA]">
              92%
            </h3>

            <div className="mt-8 h-2 overflow-hidden rounded-full bg-white/10">
              <motion.div
                initial={{ width: 0 }}
                whileInView={{ width: "92%" }}
                transition={{
                  duration: 1.5,
                }}
                className="h-full rounded-full bg-[#D6B25E]"
              />
            </div>
          </motion.div>

        </div>
      </motion.div>
    </section>
  );
}