"use client";

import {
  Sparkles,
  Brain,
  Heart,
  Moon,
  Eye,
} from "lucide-react";

import { AIConsole } from "@/components/ui/AIConsole";

import {
  useSoulAnalysis,
} from "@/hooks/useSoulAnalysis";

import {
  useState,
} from "react";

import {
  motion,
} from "framer-motion";



export function SoulScanConsole() {


  const [text, setText] =
    useState("");



  const {
    analyze,
    loading,
    result,
  } =
    useSoulAnalysis();





  async function handleSubmit() {

    if (!text.trim())
      return;


    await analyze(text);


    setText("");

  }





  return (

    <AIConsole


      icon={

        <Sparkles

          size={22}

          className="
          text-[#D6B25E]
          "

        />

      }



      eyebrow="
      EON Intelligence Scan
      "



      title="
      Decode your inner world
      "



      placeholder="
      Describe your thoughts,
      emotions or current life situation...
      "



      value={text}



      onChange={setText}



      onSubmit={handleSubmit}



      loading={loading}



      buttonText="
      Start Soul Analysis
      "



      loadingText="
      Reading your patterns...
      "




      result={

        result && (


          <motion.div


            initial={{
              opacity:0,
              y:30,
            }}



            animate={{
              opacity:1,
              y:0,
            }}



            transition={{
              duration:0.6,
            }}



            className="
            space-y-8
            rounded-[32px]
            border
            border-[#D6B25E]/20
            bg-gradient-to-br
            from-[#D6B25E]/10
            via-white/[0.03]
            to-[#8B5CF6]/10
            p-8
            "


          >





            <div

              className="
              flex
              items-center
              gap-4
              "

            >


              <div

                className="
                flex
                h-12
                w-12
                items-center
                justify-center
                rounded-2xl
                bg-[#D6B25E]/10
                "

              >

                <Brain

                  size={24}

                  className="
                  text-[#D6B25E]
                  "

                />

              </div>




              <div>

                <p

                  className="
                  text-[10px]
                  uppercase
                  tracking-[0.4em]
                  text-[#D6B25E]
                  "

                >

                  Soul Reflection

                </p>


                <p

                  className="
                  text-xs
                  text-white/40
                  "

                >

                  Generated by EON AI

                </p>


              </div>


            </div>







            <div>


              <p

                className="
                text-[11px]
                uppercase
                tracking-[0.35em]
                text-white/40
                "

              >

                Core Archetype

              </p>



              <h3

                className="
                mt-3
                text-5xl
                font-light
                text-[#F4F1EA]
                "

              >

                {result.archetype}

              </h3>


            </div>







            <div

              className="
              grid
              gap-5
              md:grid-cols-2
              "

            >





              <div

                className="
                rounded-3xl
                border
                border-white/10
                bg-white/[0.03]
                p-5
                "

              >

                <div className="
                flex
                items-center
                gap-3
                ">

                  <Heart

                    size={18}

                    className="
                    text-[#D6B25E]
                    "

                  />


                  <p className="
                  text-xs
                  uppercase
                  tracking-[0.3em]
                  text-white/40
                  ">

                    Emotion

                  </p>


                </div>


                <p className="
                mt-4
                text-xl
                text-[#F4F1EA]
                ">

                  {result.emotion}

                </p>


              </div>







              <div

                className="
                rounded-3xl
                border
                border-white/10
                bg-white/[0.03]
                p-5
                "

              >

                <div className="
                flex
                items-center
                gap-3
                ">

                  <Moon

                    size={18}

                    className="
                    text-purple-400
                    "

                  />


                  <p className="
                  text-xs
                  uppercase
                  tracking-[0.3em]
                  text-white/40
                  ">

                    Shadow

                  </p>


                </div>


                <p className="
                mt-4
                text-white/70
                leading-7
                ">

                  {result.shadow}

                </p>


              </div>




            </div>








            <div>


              <div className="
              flex
              items-center
              gap-3
              ">

                <Eye

                  size={18}

                  className="
                  text-[#D6B25E]
                  "

                />


                <p className="
                text-xs
                uppercase
                tracking-[0.3em]
                text-white/40
                ">

                  Reflection

                </p>


              </div>



              <p

                className="
                mt-4
                italic
                leading-8
                text-white/70
                "

              >

                {result.reflection}

              </p>


            </div>







            <div

              className="
              border-t
              border-white/10
              pt-6
              "

            >


              <p

                className="
                text-xs
                uppercase
                tracking-[0.35em]
                text-[#D6B25E]
                "

              >

                Personal Insight

              </p>



              <p

                className="
                mt-4
                leading-8
                text-white/80
                "

              >

                {result.insight}

              </p>


            </div>








            <div

              className="
              flex
              flex-wrap
              gap-3
              "

            >


              <span className="
              rounded-full
              border
              border-[#D6B25E]/20
              bg-[#D6B25E]/5
              px-4
              py-2
              text-[10px]
              uppercase
              tracking-[0.3em]
              text-[#D6B25E]
              ">

                Identity

              </span>



              <span className="
              rounded-full
              border
              border-white/10
              bg-white/[0.03]
              px-4
              py-2
              text-[10px]
              uppercase
              tracking-[0.3em]
              text-white/50
              ">

                Archetype

              </span>



              <span className="
              rounded-full
              border
              border-white/10
              bg-white/[0.03]
              px-4
              py-2
              text-[10px]
              uppercase
              tracking-[0.3em]
              text-white/50
              ">

                Evolution

              </span>


            </div>





            <p

              className="
              text-center
              text-[10px]
              uppercase
              tracking-[0.4em]
              text-white/30
              "

            >

              Powered by EON Intelligence Engine

            </p>



          </motion.div>

        )

      }

    />

  );

}