"use client";

import {
  Sparkles,
  Brain,
} from "lucide-react";

import { AIConsole } from "@/components/ui/AIConsole";

import {
  useSoulAnalysis,
} from "@/hooks/useSoulAnalysis";

import {
  useState,
} from "react";

import {
  motion,
} from "framer-motion";


export function SoulScanConsole() {


  const [text,setText] =
    useState("");



  const {
    analyze,
    loading,
    result,
  } =
    useSoulAnalysis();



  async function handleSubmit(){

    if(!text.trim())
      return;


    await analyze(text);


    setText("");

  }



  return (

    <AIConsole

      icon={

        <Sparkles
          size={22}
          className="
          text-[#D6B25E]
          "
        />

      }


      eyebrow="EON Intelligence Scan"


      title="Decode your personal patterns"


      description="
      AI analysis of identity, emotions,
      archetypes and subconscious patterns.
      "


      placeholder="
      Describe your thoughts,
      emotions or current life situation...
      "


      value={text}


      onChange={setText}


      onSubmit={handleSubmit}


      loading={loading}


      buttonText="Start Intelligence Scan"


      loadingText="Analyzing patterns..."


      result={

        result && (

          <motion.div

            initial={{
              opacity:0,
              y:25,
            }}

            animate={{
              opacity:1,
              y:0,
            }}

            transition={{
              duration:0.6,
            }}

            className="
            space-y-6
            rounded-[32px]
            border
            border-[#D6B25E]/20
            bg-gradient-to-br
            from-[#D6B25E]/10
            via-white/[0.03]
            to-[#8B5CF6]/10
            p-7
            "
          >

            <div
              className="
              flex
              items-center
              gap-3
              "
            >

              <div
                className="
                flex
                h-10
                w-10
                items-center
                justify-center
                rounded-2xl
                bg-[#D6B25E]/10
                "
              >

                <Brain
                  size={20}
                  className="
                  text-[#D6B25E]
                  "
                />

              </div>


              <div>

                <p
                  className="
                  text-[10px]
                  uppercase
                  tracking-[0.35em]
                  text-[#D6B25E]
                  "
                >
                  Intelligence Result
                </p>

                <p
                  className="
                  text-xs
                  text-white/40
                  "
                >
                  Generated by EON AI
                </p>

              </div>

            </div>



            <div>

              <p
                className="
                text-[11px]
                uppercase
                tracking-[0.35em]
                text-white/40
                "
              >
                Core Archetype
              </p>


              <h3
                className="
                mt-3
                text-4xl
                font-light
                text-[#F4F1EA]
                "
              >
                {result.archetype}
              </h3>

            </div>



            <div>

              <p
                className="
                text-[11px]
                uppercase
                tracking-[0.35em]
                text-white/40
                "
              >
                Personal Insight
              </p>


              <p
                className="
                mt-3
                text-base
                leading-8
                text-white/70
                "
              >
                {result.insight}
              </p>

            </div>


            <div
              className="
              flex
              flex-wrap
              gap-3
              "
            >

              <span
                className="
                rounded-full
                border
                border-[#D6B25E]/20
                bg-[#D6B25E]/5
                px-4
                py-2
                text-[10px]
                uppercase
                tracking-[0.3em]
                text-[#D6B25E]
                "
              >
                Identity
              </span>


              <span
                className="
                rounded-full
                border
                border-white/10
                bg-white/[0.03]
                px-4
                py-2
                text-[10px]
                uppercase
                tracking-[0.3em]
                text-white/50
                "
              >
                Emotion
              </span>


              <span
                className="
                rounded-full
                border
                border-white/10
                bg-white/[0.03]
                px-4
                py-2
                text-[10px]
                uppercase
                tracking-[0.3em]
                text-white/50
                "
              >
                Archetype
              </span>

            </div>



            <div
              className="
              border-t
              border-white/10
              pt-5
              "
            >

              <p
                className="
                text-[10px]
                uppercase
                tracking-[0.4em]
                text-white/30
                "
              >
                Powered by EON Intelligence Engine
              </p>

            </div>


          </motion.div>

        )

      }


    />

  );

}